version: '3.8'
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      development:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports: 
      - 3000:3000
    volumes:
      - .:/aplicacao
    networks:
      development:
  