name: "CI"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ./aplicacao
jobs:
  build:
    name: "Execução da build do projeto"
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Run docker
        run: docker-compose up --build -d
  test:
      name: "Execução dos testes"
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: reset database
          run: docker-compose run app rails db:reset
        - name: Run tests
          run: docker-compose run app rspec